// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJyC4YqUhKbR4VGmVTdyjuWQsvxMSo3bY',
    appId: '1:1095355106007:web:210def8d32e3ab550f6692',
    messagingSenderId: '1095355106007',
    projectId: 'ecommerce-app-5eed4',
    authDomain: 'ecommerce-app-5eed4.firebaseapp.com',
    storageBucket: 'ecommerce-app-5eed4.appspot.com',
    measurementId: 'G-PLDSMCY2MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJNL68M9Sxxtb4RdQL_5w_H3-FA45TGCA',
    appId: '1:1095355106007:android:25b39b60dc9176360f6692',
    messagingSenderId: '1095355106007',
    projectId: 'ecommerce-app-5eed4',
    storageBucket: 'ecommerce-app-5eed4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFz7CxSAfaPHR_04ewe2EX5PSuBWJpHIs',
    appId: '1:1095355106007:ios:8b127a5288d3f82b0f6692',
    messagingSenderId: '1095355106007',
    projectId: 'ecommerce-app-5eed4',
    storageBucket: 'ecommerce-app-5eed4.appspot.com',
    iosBundleId: 'com.example.ecommerceCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFz7CxSAfaPHR_04ewe2EX5PSuBWJpHIs',
    appId: '1:1095355106007:ios:66b989cba8e562d30f6692',
    messagingSenderId: '1095355106007',
    projectId: 'ecommerce-app-5eed4',
    storageBucket: 'ecommerce-app-5eed4.appspot.com',
    iosBundleId: 'com.example.ecommerceCloneApp.RunnerTests',
  );
}
